version: '3.1'

services: 
  minio:
    restart: always
    image: minio/minio:latest
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: AKID123456
      MINIO_SECRET_KEY: AKEY123456
    command:
      - server
      - /data
    networks:
      - inner

networks:
  inner:
    ipam:
      driver: default
      config:
        - subnet: "169.254.102.0/24"

